---
output: pdf_document
---
<!-- The {.unnumbered} option here means that the introduction will be "Chapter 0." -->

# Introduction {.unnumbered}

  Spatial point patterns, data in the form of a set of points on the plane, emerge frequently in practice. Their remarkable theoretical properties permit a surprisingly unified study of data as seemingly disparate as the locations of stars in the sky, the dispersal of trees in a forest, and the occurrences of crime in a neighborhood. 
  
  As a simple illustration, figure 1 presents the locations of trees in a New Zealand forest plot. Each point represents a tree and its location represents its position in an approximately 140 by 85 foot forest plot. These data were gathered from a complete sampling of the forest plot and do not contain additional information on the underlying features of the land quality, the type of tree, or the size of the tree. The uninformed statistician must proceed through inference solely based upon these events, their locations in the plot, and their locations relative to one another. This is actually a remarkably rich amount of information. Statistical models can detect clustering, regularity, variation in the underlying region, and event intensity. However, many methods rely on cencuses that accountfor every event in an area. This form of sampling is often expensive, time-consuming, and error prone. 
  
Cheaper, less time-consuming sampling methods exist. One in particular, T-square sampling, has a rich theoretical literature which has found methods for detecting clustering and regularity. In this thesis, I hope to expand the, rather empty, corpus on an even simpler sampling scheme: k-trees sampling. 

K-tree sampling schemes find the k-nearest events to points specified in a pre-determined array. Little research has been done to determine how clustering and regularity could be detected under such a sampling scheme. This is because of the inability to reliably compute point to point nearest neighbors with sampling. I do not try and resolve this issue. Instead, I work with a number of datasets containing data collected through the 1-tree sampling of the same plant in a number of bogs. I assume both that there are two causes of apparent clustering, event based (typically considered "real" clustering) and underlying region based, and that event based clustering is consistent from dataset to dataset, while underlying region clustering varies. Thus, we can incorporate event based clustering mechanisms into future models of the same process.   


